name: Lint


on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/**/*.clj'
      - 'src/**/*.cljs'
      - 'src/**/*.cljc'
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  clj-kondo:
    name: Lint with clj-kondo
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.03.09'
      - name: Lint
        run: |
          clj-kondo --lint src
          # --config .clj-kondo/config.edn
      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
